### ISSUE TITLE
Missing file ornaments/examples/lambda2.lagda

### ISSUE THREAD

**Issue by gallais** [Lapin0t/induction-recursion#1]
The Makefile mentions a file `ornaments/examples/lambda2.lagda` and `ornaments.tex` does
indeed depend on it but it's missing from the repo so it's impossible to build the pdf.

**Comment by Lapin0t** [comment]
Nice catch, i just pushed it (3f6be3f).

**Comment by gallais** [comment]
Perfect. Thanks!
